export interface Storybook {
  id: string;
  slug: string;
  title: string;
  language: 'es' | 'en';
  coverUrl?: string; // Optional, will fallback to page-1.jpg if undefined
  pageCount: number;
  pages: string[];
  bilingualPairId?: string;
}

const generatePages = (slug: string, count: number) => 
  Array.from({ length: count }, (_, i) => `storybooks/${slug}/assets/page-${i + 1}.jpg`);

export const SPANISH_STORYBOOKS: Storybook[] = [
  {
    id: 'es-1',
    slug: 'iluminacion-nocturna',
    title: 'Iluminación Nocturna y Mitigación del Impacto en la Fauna',
    language: 'es',
    pageCount: 9,
    pages: generatePages('iluminacion-nocturna', 9),
    bilingualPairId: 'en-1',
  },
  {
    id: 'es-2',
    slug: 'sbn-drenaje-sostenible',
    title: 'SBN y drenaje sostenible (SUDS)',
    language: 'es',
    pageCount: 8,
    pages: generatePages('sbn-drenaje-sostenible', 8),
    bilingualPairId: 'en-2',
  },
  {
    id: 'es-3',
    slug: 'ruido-operativo',
    title: 'Ruido operativo y biodiversidad',
    language: 'es',
    pageCount: 10,
    pages: generatePages('ruido-operativo', 10),
    bilingualPairId: 'en-3',
  },
  {
    id: 'es-4',
    slug: 'conectividad-ecologica',
    title: 'Conectividad Ecológica / Corredor Verde',
    language: 'es',
    pageCount: 10,
    pages: generatePages('conectividad-ecologica', 10),
    bilingualPairId: 'en-4',
  },
  {
    id: 'es-5',
    slug: 'especies-invasoras',
    title: 'Especies Invasoras: Estrategias de Prevención y Control Industrial',
    language: 'es',
    pageCount: 10,
    pages: generatePages('especies-invasoras', 10),
    bilingualPairId: 'en-5',
  },
  {
    id: 'es-6',
    slug: 'ecosistema-operativo',
    title: 'El Ecosistema Operativo: Microhábitats en el Paisaje Industrial',
    language: 'es',
    pageCount: 10,
    pages: generatePages('ecosistema-operativo', 10),
    bilingualPairId: 'en-6',
  },
  {
    id: 'es-7',
    slug: 'gestion-hidrica-humedales',
    title: 'Gestión Hídrica y Humedales Estacionales en Infraestructura Aeronáutica',
    language: 'es',
    pageCount: 10,
    pages: generatePages('gestion-hidrica-humedales', 10),
    bilingualPairId: 'en-7',
  },
  {
    id: 'es-8',
    slug: 'gestion-residuos-verdes',
    title: 'Gestión de residuos verdes y compostaje',
    language: 'es',
    pageCount: 10,
    pages: generatePages('gestion-residuos-verdes', 10),
    bilingualPairId: 'en-8',
  },
  {
    id: 'es-9',
    slug: 'monitoreo-kpis',
    title: 'Monitoreo y KPIs de biodiversidad en planta',
    language: 'es',
    pageCount: 10,
    pages: generatePages('monitoreo-kpis', 10),
    bilingualPairId: 'en-9',
  },
  {
    id: 'es-10',
    slug: 'polinizadores-industrial',
    title: 'Polinizadores en entorno industrial',
    language: 'es',
    pageCount: 10,
    pages: generatePages('polinizadores-industrial', 10),
    bilingualPairId: 'en-11',
  },
  {
    id: 'es-11',
    slug: 'suelo-desellado',
    title: 'Suelo y desellado',
    language: 'es',
    pageCount: 10,
    pages: generatePages('suelo-desellado', 10),
    bilingualPairId: 'en-12',
  },
  {
    id: 'es-12',
    slug: 'fauna-urbana',
    title: 'Biblioteca de Biodiversidad en Fábrica: Convivencia con fauna urbana',
    language: 'es',
    pageCount: 10,
    pages: generatePages('fauna-urbana', 10),
    bilingualPairId: 'en-10',
  },
];

export const ENGLISH_STORYBOOKS: Storybook[] = [
  {
    id: 'en-1',
    slug: 'nocturnal-lighting',
    title: 'Nocturnal Lighting and Fauna Impact Mitigation',
    language: 'en',
    pageCount: 9,
    pages: generatePages('nocturnal-lighting', 9),
    bilingualPairId: 'es-1',
  },
  {
    id: 'en-2',
    slug: 'nbs-suds',
    title: 'NBS and Sustainable Drainage Systems (SuDS)',
    language: 'en',
    pageCount: 8,
    pages: generatePages('nbs-suds', 8),
    bilingualPairId: 'es-2',
  },
  {
    id: 'en-3',
    slug: 'operational-noise',
    title: 'Operational Noise and Biodiversity',
    language: 'en',
    pageCount: 10,
    pages: generatePages('operational-noise', 10),
    bilingualPairId: 'es-3',
  },
  {
    id: 'en-4',
    slug: 'ecological-connectivity',
    title: 'Ecological Connectivity / Green Corridor',
    language: 'en',
    pageCount: 9,
    pages: generatePages('ecological-connectivity', 9),
    bilingualPairId: 'es-4',
  },
  {
    id: 'en-5',
    slug: 'invasive-species-en',
    title: 'Invasive Species: Industrial Prevention and Control Strategies',
    language: 'en',
    pageCount: 10,
    pages: generatePages('invasive-species-en', 10),
    bilingualPairId: 'es-5',
  },
  {
    id: 'en-6',
    slug: 'operational-ecosystem',
    title: 'The Operational Ecosystem: Microhabitats in the Industrial Landscape',
    language: 'en',
    pageCount: 10,
    pages: generatePages('operational-ecosystem', 10),
    bilingualPairId: 'es-6',
  },
  {
    id: 'en-7',
    slug: 'water-management-wetlands',
    title: 'Water Management and Seasonal Wetlands in Aeronautical Infrastructure',
    language: 'en',
    pageCount: 9,
    pages: generatePages('water-management-wetlands', 9),
    bilingualPairId: 'es-7',
  },
  {
    id: 'en-8',
    slug: 'green-waste-management',
    title: 'Green Waste Management and Composting',
    language: 'en',
    pageCount: 10,
    pages: generatePages('green-waste-management', 10),
    bilingualPairId: 'es-8',
  },
  {
    id: 'en-9',
    slug: 'biodiversity-monitoring',
    title: 'Biodiversity Monitoring and KPIs at the Plant',
    language: 'en',
    pageCount: 10,
    pages: generatePages('biodiversity-monitoring', 10),
    bilingualPairId: 'es-9',
  },
  {
    id: 'en-10',
    slug: 'urban-fauna-coexistence',
    title: 'Factory Biodiversity Library: Urban Fauna Coexistence',
    language: 'en',
    pageCount: 9,
    pages: generatePages('urban-fauna-coexistence', 9),
    bilingualPairId: 'es-12',
  },
  {
    id: 'en-11',
    slug: 'pollinators-industrial-en',
    title: 'Factory Biodiversity Library: Pollinators in Industrial Environments',
    language: 'en',
    pageCount: 10,
    pages: generatePages('pollinators-industrial-en', 10),
    bilingualPairId: 'es-10',
  },
  {
    id: 'en-12',
    slug: 'soil-de-sealing',
    title: 'Soil De-sealing',
    language: 'en',
    pageCount: 10,
    pages: generatePages('soil-de-sealing', 10),
    bilingualPairId: 'es-11',
  },
];

export const ALL_STORYBOOKS = [...SPANISH_STORYBOOKS, ...ENGLISH_STORYBOOKS];
