import type { NativeStorybook } from '../nativeStorybooks.types';

export const BOOK_RUIDO_OPERATIVO: NativeStorybook = {
  "title": "Ruido operativo y naturaleza",
  "author": "Almudena Urbieta",
  "chapters": [
    {"number":1,"title":"Ruido operativo y naturaleza","paragraphs":["Ruido operativo y biodiversidad: Manual de mitigación técnica en infraestructuras industriales. Esta entrega de la 'Biblioteca de Biodiversidad en Fábrica’ analiza el impacto de la presión sonora sobre los servicios ecosistémicos. La gestión del paisaje acústico no es una acción estética, sino un requisito de ingeniería para la resiliencia operativa y la preservación del capital natural en entornos de alta actividad."],"layout":"image-left"},
    {"number":2,"title":"Contexto Estratégico","paragraphs":["El ruido industrial trasciende el riesgo laboral para convertirse en una externalidad ambiental crítica. El incumplimiento de los umbrales de emisión sonora puede comprometer la licencia social para operar y derivar en contingencias legales vinculadas a la protección de especies protegidas. Una estrategia de sostenibilidad robusta integra la acústica en el diseño de procesos para evitar la fragmentación de hábitats por contaminación sonora."],"layout":"image-right"},
    {"number":3,"title":"Marco Científico","paragraphs":["El Fenómeno del Enmascaramiento: La biodiversidad local depende de señales acústicas para la comunicación, defensa y reproducción. El ruido operativo genera un 'enmascaramiento' que interrumpe estas frecuencias vitales. Especialmente en aves y quirópteros, el ruido de fondo constante reduce el éxito reproductivo y altera los patrones de alimentación, degradando la funcionalidad biológica de los corredores verdes perimetrales."],"layout":"image-left"},
    {"number":4,"title":"Análisis de Campo","paragraphs":["Impacto Logístico: El flujo de vehículos pesados y la actividad en los muelles de carga generan picos de baja frecuencia que se propagan a grandes distancias. Estos eventos acústicos discretos pero intensos actúan como barreras invisibles para la fauna terrestre, provocando el abandono de nichos ecológicos y reduciendo la biodiversidad en las zonas de transición entre la fábrica y el medio natural."],"layout":"image-right"},
    {"number":5,"title":"Análisis de Campo","paragraphs":["Emisiones en Producción: Las líneas de montaje y sistemas neumáticos operan frecuentemente en rangos de 85 a 105 dB. Esta presión sonora continua crea zonas de exclusión biológica persistentes. La auditoría técnica debe identificar no solo la intensidad, sino la persistencia temporal de estas fuentes para diseñar medidas de mitigación que respeten los periodos de mayor sensibilidad de la fauna local."],"layout":"image-left"},
    {"number":6,"title":"Ingeniería de Soluciones","paragraphs":["Atenuación Estructural: La instalación de barreras acústicas con materiales absorbentes y deflectores optimizados reduce significativamente la huella sonora externa. Estas soluciones deben integrarse con protocolos de 'ventanas de silencio' durante los ciclos circadianos críticos de la biodiversidad, transformando la infraestructura pasiva en un sistema dinámico de protección ambiental."],"layout":"image-right"},
    {"number":7,"title":"Ingeniería de Soluciones","paragraphs":["Control de Vibraciones: El ruido transmitido por estructuras sólidas es a menudo ignorado pero altamente impactante. El uso de montajes antivibratorios y silentblocks en equipos de gran potencia minimiza la propagación de bajas frecuencias a través del suelo. Un mantenimiento predictivo centrado en la lubricación y el ajuste de componentes es la primera barrera técnica contra la contaminación acústica."],"layout":"image-left"},
    {"number":8,"title":"Evaluación y Auditoría IoT","paragraphs":["La implementación de redes de sensores IoT permite una monitorización continua y en tiempo real de los niveles de emisión. Estos datos alimentan gemelos digitales que predicen el impacto acústico ante cambios en el ritmo de producción. La transparencia en los datos es el protocolo fundamental anti-greenwashing, permitiendo auditorías externas verificables y precisas."],"layout":"image-right"},
    {"number":9,"title":"Guía de Acción y Checklist Técnico","paragraphs":["El protocolo de actuación se resume en: 1. Caracterización espectral de focos emisores; 2. Implementación de aislantes en origen; 3. Programación operativa según ciclos biológicos; 4. Auditoría de verificación mediante red de sensores. La excelencia en la ingeniería de infraestructuras aeronáuticas e industriales exige hoy la integración total de la biodiversidad en sus parámetros de diseño."],"layout":"image-left"}
  ]
};
