export type Language = 'es' | 'en';
export interface Chapter { id: number; title: string; summary: string; body: string[]; practice: string; }
export interface Storybook { id: string; slug: string; title: string; subtitle: string; language: Language; theme: string; colour: string; icon: string; pdfPath: string; bilingualPairId: string; chapters: Chapter[]; }
type Topic = { slug: string; colour: string; icon: string; es: [string,string,string,string]; en: [string,string,string,string] };
const topics: Topic[] = [
  {slug:'iluminacion-nocturna',colour:'#443a63',icon:'◐',es:['Iluminación nocturna','Diseñar luz útil sin desorientar la vida nocturna','luz','fauna nocturna'],en:['Nocturnal lighting','Designing useful light without disorienting nocturnal life','lighting','nocturnal fauna']},
  {slug:'sbn-drenaje-sostenible',colour:'#246c73',icon:'≈',es:['SBN y drenaje sostenible','Agua, suelo y soluciones basadas en la naturaleza','drenaje','agua y suelo'],en:['Nature-based drainage','Water, soil and nature-based solutions','drainage','water and soil']},
  {slug:'ruido-operativo',colour:'#8b4d3b',icon:'⌁',es:['Ruido operativo y naturaleza','Gestionar el sonido como una presión ambiental','ruido','fauna y comunidades'],en:['Operational noise and nature','Managing sound as an environmental pressure','noise','fauna and communities']},
  {slug:'conectividad-ecologica',colour:'#49723c',icon:'↝',es:['Conectividad ecológica','Mantener rutas funcionales en paisajes industriales','conectividad','hábitats conectados'],en:['Ecological connectivity','Keeping functional routes in industrial landscapes','connectivity','connected habitats']},
  {slug:'especies-invasoras',colour:'#7a5030',icon:'⌘',es:['Especies invasoras','Prevención y respuesta en instalaciones industriales','especies invasoras','ecosistemas locales'],en:['Invasive species','Prevention and response at industrial sites','invasive species','local ecosystems']},
  {slug:'ecosistema-operativo',colour:'#385f57',icon:'✦',es:['El ecosistema operativo','Microhábitats y decisiones cotidianas','microhábitats','vida cotidiana del recinto'],en:['The operational ecosystem','Microhabitats and everyday decisions','microhabitats','everyday site life']},
  {slug:'gestion-hidrica-humedales',colour:'#2b678f',icon:'◒',es:['Gestión hídrica y humedales','Infraestructura aeronáutica sensible al agua','humedales','ciclos del agua'],en:['Water management and wetlands','Aeronautical infrastructure that works with water','wetlands','water cycles']},
  {slug:'gestion-residuos-verdes',colour:'#5c7131',icon:'♧',es:['Residuos verdes y compostaje','Convertir biomasa en un recurso controlado','residuos verdes','suelo y recursos'],en:['Green waste and composting','Turning biomass into a controlled resource','green waste','soil and resources']},
  {slug:'monitoreo-kpis',colour:'#63569a',icon:'◫',es:['Monitoreo ambiental y KPIs','Medir para decidir y aprender','indicadores','decisiones verificables'],en:['Environmental monitoring and KPIs','Measuring to decide and learn','indicators','verifiable decisions']},
  {slug:'polinizadores-industrial',colour:'#aa7430',icon:'✿',es:['Polinizadores industriales','Hábitats funcionales más allá del jardín','polinizadores','plantas y alimento'],en:['Pollinators in industry','Functional habitats beyond a garden','pollinators','plants and food']},
  {slug:'suelo-desellado',colour:'#71533b',icon:'▦',es:['Suelo y desellado','Recuperar funciones bajo superficies duras','suelo','infiltración y vida'],en:['Soil de-sealing','Recovering functions beneath hard surfaces','soil','infiltration and life']},
  {slug:'fauna-urbana',colour:'#535c6c',icon:'◉',es:['Convivencia con fauna urbana','Seguridad, bienestar y coexistencia','fauna urbana','personas y especies'],en:['Urban fauna coexistence','Safety, welfare and coexistence','urban fauna','people and species']}
];
const chaptersEs=(name:string,focus:string,system:string):Chapter[]=>[
 {id:1,title:'Abrir la pregunta',summary:`Qué problema resuelve ${name.toLowerCase()} y por qué importa.`,body:[`${name} no es un elemento decorativo: condiciona cómo funciona ${system} y cómo se toman decisiones en un entorno industrial. Este capítulo sitúa el reto, identifica a las personas y sistemas afectados y separa hechos, supuestos y prioridades.`,`Una buena decisión empieza por describir el contexto: actividad, lugar, estacionalidad, receptores sensibles y restricciones de seguridad. Esa lectura evita soluciones genéricas que no funcionan en el terreno.`],practice:`Describe una situación concreta en la que ${focus} pueda crear un riesgo u oportunidad.`},
 {id:2,title:'Entender el sistema',summary:'Relaciones, mecanismos y límites que conviene reconocer.',body:[`Los efectos aparecen por cadenas de causa y efecto. Una actuación puede modificar recursos, comportamiento o conectividad y producir consecuencias directas e indirectas. Mapear esas relaciones permite anticipar conflictos antes de que se conviertan en incidencias.`,`No todo cambio es igual de relevante. La escala, duración, frecuencia y reversibilidad ayudan a priorizar; también importa la vulnerabilidad del receptor y la calidad de la evidencia disponible.`],practice:`Traza una cadena simple: actividad → presión → receptor → consecuencia.`},
 {id:3,title:'Observar con criterio',summary:'Datos suficientes, sin medir por medir.',body:[`La observación útil responde a una decisión. Define una línea de base, selecciona pocos indicadores que puedan repetirse y registra método, fecha, lugar y limitaciones. Los datos comparables son más valiosos que una fotografía aislada.`,`Combina recorridos de campo, registros operativos y conocimiento local. Si la incertidumbre es alta, documentarla es más honesto y más útil que convertir una hipótesis en una conclusión.`],practice:`Elige dos indicadores para seguir ${focus} durante tres meses y explica qué decisión informarán.`},
 {id:4,title:'Diseñar la respuesta',summary:'Prevenir primero; compensar solo cuando sea necesario.',body:[`La jerarquía de mitigación orienta la respuesta: evitar, minimizar, restaurar y, solo después, considerar medidas complementarias. Aplicarla desde el diseño suele costar menos y ofrece resultados más sólidos que corregir tarde.`,`Las medidas deben ser operables: responsable, plazo, recursos, criterio de éxito y condición de revisión. Una acción sin mantenimiento ni gobernanza puede perder su función rápidamente.`],practice:`Formula una medida preventiva y define cómo comprobarías que funciona.`},
 {id:5,title:'Aplicar en operación',summary:'Convertir el principio en una rutina segura.',body:[`La aplicación real se integra en planificación, compras, mantenimiento, permisos de trabajo y gestión de contratistas. El objetivo no es añadir una tarea aislada, sino incorporar una comprobación proporcional al riesgo en el flujo habitual.`,`Las instrucciones deben ser claras para quien actúa: qué observar, cuándo detenerse, a quién avisar y qué registro conservar. La comunicación temprana reduce retrabajo y evita decisiones improvisadas.`],practice:`Identifica el punto de una rutina operativa donde incluirías una comprobación de ${focus}.`},
 {id:6,title:'Decidir con evidencia',summary:'Comparar alternativas sin promesas excesivas.',body:[`Compara opciones mediante criterios transparentes: seguridad, desempeño técnico, coste de ciclo de vida, impacto potencial, mantenimiento y evidencia. Explica los compromisos; la sostenibilidad no consiste en declarar que toda opción tiene solo beneficios.`,`Una afirmación fiable indica alcance, condiciones y límites. Si no se puede verificar un resultado, preséntalo como intención o hipótesis, nunca como logro consolidado.`],practice:`Compara dos alternativas con tres criterios y señala una incertidumbre relevante.`},
 {id:7,title:'Aprender y avanzar',summary:'Cerrar el ciclo con seguimiento y mejora.',body:[`Revisa los resultados en intervalos definidos y adapta la medida si no produce el efecto esperado. Comparte tanto los aciertos como los límites: el aprendizaje acumulado convierte una actuación puntual en capacidad organizativa.`,`El capítulo final conecta ${name.toLowerCase()} con la gestión ambiental, la transparencia y el aprendizaje continuo. Una buena historia termina con una próxima decisión concreta, no con una conclusión decorativa.`],practice:`Define la próxima revisión, la evidencia que llevarías y la decisión que podrías cambiar.`}
];
const chaptersEn=(name:string,focus:string,system:string):Chapter[]=>[
 {id:1,title:'Frame the question',summary:`What ${name.toLowerCase()} solves and why it matters.`,body:[`${name} is not decorative: it shapes how ${system} works and how decisions are made in an industrial setting. This chapter frames the challenge, identifies affected people and systems, and separates facts from assumptions and priorities.`,`A sound decision starts with context: activity, location, seasonality, sensitive receptors and safety constraints. This prevents generic solutions that fail in the real setting.`],practice:`Describe one situation in which ${focus} could create a risk or an opportunity.`},
 {id:2,title:'Understand the system',summary:'Relationships, mechanisms and limits worth recognising.',body:[`Effects arise through cause-and-effect chains. An intervention can alter resources, behaviour or connectivity and create direct and indirect consequences. Mapping those links helps anticipate conflicts before they become incidents.`,`Not every change has the same significance. Scale, duration, frequency and reversibility help prioritise; receptor vulnerability and the quality of available evidence matter too.`],practice:'Draw a simple chain: activity → pressure → receptor → consequence.'},
 {id:3,title:'Observe with purpose',summary:'Enough evidence, without measuring for its own sake.',body:[`Useful observation answers a decision. Set a baseline, select a small number of repeatable indicators, and record method, date, place and limitations. Comparable evidence is more valuable than a single snapshot.`,`Combine field observations, operational records and local knowledge. When uncertainty is high, documenting it is more useful than turning a hypothesis into a conclusion.`],practice:`Choose two indicators to follow ${focus} for three months and explain the decision they would inform.`},
 {id:4,title:'Design the response',summary:'Avoid first; compensate only when necessary.',body:[`The mitigation hierarchy guides a response: avoid, minimise, restore and only then consider complementary measures. Applying it during design usually costs less and produces stronger outcomes than correcting late.`,`Measures must be operable: owner, timing, resources, success criterion and review trigger. An action with no maintenance or governance can quickly lose its function.`],practice:'Draft one preventive measure and say how you would check that it works.'},
 {id:5,title:'Embed it in operations',summary:'Turn a principle into a safe routine.',body:[`Real implementation is embedded in planning, procurement, maintenance, permits to work and contractor management. The goal is not an isolated task, but a risk-proportionate check in the normal flow of work.`,`Instructions must be clear for the person acting: what to observe, when to stop, who to notify and what record to retain. Early communication reduces rework and improvised decisions.`],practice:`Identify the point in an operational routine where a ${focus} check belongs.`},
 {id:6,title:'Decide with evidence',summary:'Compare options without overclaiming.',body:[`Compare alternatives through transparent criteria: safety, technical performance, life-cycle cost, potential impact, maintenance and evidence. Explain trade-offs; sustainability does not mean claiming every option has only benefits.`,`A reliable claim states its scope, conditions and limits. If an outcome cannot be verified, present it as an intention or hypothesis, never as an established achievement.`],practice:'Compare two options using three criteria and name one material uncertainty.'},
 {id:7,title:'Learn and move forward',summary:'Close the loop through monitoring and improvement.',body:[`Review outcomes at defined intervals and adapt the measure if it does not create the expected effect. Share both successes and limitations: accumulated learning turns a one-off intervention into organisational capability.`,`This final chapter links ${name.toLowerCase()} to environmental management, transparency and continuous learning. A good story ends with a concrete next decision, not a decorative conclusion.`],practice:'Define the next review, the evidence you would bring and the decision you might change.'}
];
export const SPANISH_STORYBOOKS:Storybook[]=topics.map((t,i)=>({id:`es-${i+1}`,slug:t.slug,title:t.es[0],subtitle:t.es[1],language:'es',theme:t.es[2],colour:t.colour,icon:t.icon,pdfPath:`pdfs/${t.slug}.pdf`,bilingualPairId:`en-${i+1}`,chapters:chaptersEs(t.es[0],t.es[2],t.es[3])}));
const englishSlugs=['nocturnal-lighting','nbs-suds','operational-noise','ecological-connectivity','invasive-species-en','operational-ecosystem','water-management-wetlands','green-waste-management','biodiversity-monitoring','pollinators-industrial-en','soil-de-sealing','urban-fauna-coexistence'];
export const ENGLISH_STORYBOOKS:Storybook[]=topics.map((t,i)=>({id:`en-${i+1}`,slug:englishSlugs[i],title:t.en[0],subtitle:t.en[1],language:'en',theme:t.en[2],colour:t.colour,icon:t.icon,pdfPath:`pdfs/${englishSlugs[i]}.pdf`,bilingualPairId:`es-${i+1}`,chapters:chaptersEn(t.en[0],t.en[2],t.en[3])}));
export const ALL_STORYBOOKS=[...SPANISH_STORYBOOKS,...ENGLISH_STORYBOOKS];
